on:
  schedule:
  - cron: '15 19 * * *'
  push:
    branches:
    - master

env:
  TZ: Asia/Dhaka

jobs:
  check_balance_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: python desco.py
      env:
        DESCO_PREPAID_ACCOUNT_ID: ${{ secrets.DESCO_PREPAID_ACCOUNT_ID }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
